{
 "title": "Node Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "world map", "type": "geomap", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Operating System Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"192.168.0.9:9100\"}"
    }
   ]
  },
  {
   "title": "WIFI UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_up{device=\"wlan0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\", instance=\"192.168.0.9:9090\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"wlan0\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"192.168.0.9:9100\"}[30s])) by (cpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(node_hwmon_temp_celsius) by (sensor)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}